import type { GameOptions } from "./game_options";
import { patterns, type PatternDataDict } from "./pattern.ts";

const typeSafeObjectFromEntries = <
  const T extends ReadonlyArray<readonly [PropertyKey, unknown]>,
>(
  entries: T,
): { [K in T[number] as K[0]]: K[1] } => {
  return Object.fromEntries(entries) as { [K in T[number] as K[0]]: K[1] };
};

function fill_in(data: {
  [key: string]: { yaku?: number; dora?: number; fu?: number };
}): PatternDataDict {
  return typeSafeObjectFromEntries(
    patterns.map((key) => [
      key,
      {
        yaku: 0,
        dora: 0,
        fu: 0,
        ...data[key],
      },
    ]),
  );
}

const default_pattern_data = {
  BLESSING_OF_HEAVEN: { yaku: 20 },
  BLESSING_OF_EARTH: { yaku: 19 },
  LITTLE_THREE_DRAGONS: { yaku: 5 },
  BIG_THREE_DRAGONS: { yaku: 8 },
  FOUR_LITTLE_WINDS: { yaku: 12 },
  FOUR_BIG_WINDS: { yaku: 16 },
  FOUR_CONCEALED_TRIPLETS: { yaku: 12 },
  FOUR_CONCEALED_TRIPLETS_1_SIDED_WAIT: { yaku: 12 },
  ALL_HONOURS: { yaku: 10 },
  ALL_GREENS: { yaku: 16 },
  ALL_TERMINALS: { yaku: 13 },
  THIRTEEN_ORPHANS: { yaku: 13 },
  THIRTEEN_ORPHANS_13_SIDED_WAIT: { yaku: 13 },
  FOUR_QUADS: { yaku: 18 },
  NINE_GATES: { yaku: 11 },
  TRUE_NINE_GATES: { yaku: 19 },
  RIICHI: { yaku: 1 },
  DOUBLE_RIICHI: { yaku: 2 },
  IPPATSU: { yaku: 1 },
  ALL_SEQUENCES: { yaku: 1 },
  ALL_SIMPLES: { yaku: 1 },
  PURE_STRAIGHT: { yaku: 3 },
  ALL_TRIPLETS: { yaku: 3 },
  HALF_FLUSH: { yaku: 3 },
  FULL_FLUSH: { yaku: 7 },
  SEVEN_PAIRS: { yaku: 3 },
  HALF_OUTSIDE_HAND: { yaku: 2 },
  FULLY_OUTSIDE_HAND: { yaku: 4 },
  PURE_DOUBLE_SEQUENCE: { yaku: 1 },
  TWICE_PURE_DOUBLE_SEQUENCE: { yaku: 4 },
  PURE_TRIPLE_SEQUENCE: { yaku: 6 },
  PURE_QUADRUPLE_SEQUENCE: { yaku: 12 },
  MIXED_TRIPLE_SEQUENCE: { yaku: 2 },
  THREE_CONCEALED_TRIPLETS: { yaku: 3 },
  THREE_QUADS: { yaku: 4 },
  TRIPLE_TRIPLETS: { yaku: 4 },
  ALL_TERMINALS_AND_HONOURS: { yaku: 3 },
  SEAT_WIND: { yaku: 1 },
  PREVALENT_WIND: { yaku: 1 },
  NORTH_WIND: { yaku: 1 },
  WHITE_DRAGON: { yaku: 1 },
  GREEN_DRAGON: { yaku: 1 },
  RED_DRAGON: { yaku: 1 },
  EYES: { yaku: 1 },
  NO_CALLS: { yaku: 1 },
  ROBBING_A_KAN: { yaku: 1 },
  UNDER_THE_SEA: { yaku: 1 },
  UNDER_THE_RIVER: { yaku: 1 },
  AFTER_A_FLOWER: { yaku: 1 },
  AFTER_A_KAN: { yaku: 2 },
  DORA: { dora: 1 },
  URA_DORA: { dora: 1 },
  NO_FLOWERS: { dora: 1 },
  SEAT_FLOWER: { dora: 1 },
  SET_OF_FLOWERS: { dora: 2 },
  FIVE_FLOWERS: { dora: 2 },
  SEVEN_FLOWERS: { dora: 2 },
  TWO_SETS_OF_FLOWERS: { dora: 8 },
  DRAW: { yaku: 1 },
  CLOSED_WAIT: { fu: 2 },
  EDGE_WAIT: { fu: 2 },
  PAIR_WAIT: { fu: 2 },
  SIMPLE_OPEN_TRIPLET: { fu: 2 },
  ORPHAN_OPEN_TRIPLET: { fu: 4 },
  SIMPLE_CLOSED_TRIPLET: { fu: 4 },
  ORPHAN_CLOSED_TRIPLET: { fu: 8 },
  SIMPLE_OPEN_QUAD: { fu: 8 },
  ORPHAN_OPEN_QUAD: { fu: 16 },
  SIMPLE_CLOSED_QUAD: { fu: 16 },
  ORPHAN_CLOSED_QUAD: { fu: 32 },
  YAKUHAI_PAIR: { fu: 2 },
  OPEN_PINFU: { fu: 2 },
  NO_CALLS_RON: { fu: 10 },
  NON_PINFU_TSUMO: { fu: 2 },
};

const default_preset = {
  game_length_wind_rounds: 1,
  game_length_sub_rounds: 0,
  use_flowers: true,
  auto_replace_flowers: true,
  min_yaku: 0,
  allow_riichi: true,
  riichi_cost: 0,
  can_riichi_negative_score: true,
  allow_rob_added_kan: true,
  allow_thirteen_orphans_rob_closed_kan: true,
  allow_rob_closed_kan: false,
  use_temporary_furiten: true,
  use_riichi_furiten: true,
  use_own_discard_furiten: true,
  end_last_round_if_dealer_ahead: false,
  show_waits: true,
  show_shanten_info: false,
  max_kan_count: 4,
  max_dora_count: 5,
  start_dora_count: 1,
  dead_wall_additional_tiles: 0,
  start_score: 0,
  calculate_fu: true,
  base_fu: 20,
  seven_pairs_use_fixed_fu: true,
  seven_pairs_fixed_fu: 25,
  round_up_fu: false,
  round_up_points: false,
  base_score_limits: [
    { han: 6, score: 6400 },
    { han: 10, score: 12800 },
  ],
  pattern_data: fill_in(default_pattern_data),
};

export const default_4player_preset: GameOptions = {
  ...default_preset,
  player_count: 4,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 2,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1,
  score_nondealer_tsumo_dealer_multiplier: 2,
};

export const default_3player_preset: GameOptions = {
  ...default_preset,
  player_count: 3,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 3,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1.5,
  score_nondealer_tsumo_dealer_multiplier: 2.5,
};

const riichi_pattern_data = {
  BLESSING_OF_HEAVEN: { yaku: 13 },
  BLESSING_OF_EARTH: { yaku: 13 },
  LITTLE_THREE_DRAGONS: { yaku: 2 },
  BIG_THREE_DRAGONS: { yaku: 13 },
  FOUR_LITTLE_WINDS: { yaku: 13 },
  FOUR_BIG_WINDS: { yaku: 13 },
  FOUR_CONCEALED_TRIPLETS: { yaku: 13 },
  FOUR_CONCEALED_TRIPLETS_1_SIDED_WAIT: { yaku: 13 },
  ALL_HONOURS: { yaku: 13 },
  ALL_GREENS: { yaku: 13 },
  ALL_TERMINALS: { yaku: 13 },
  THIRTEEN_ORPHANS: { yaku: 13 },
  THIRTEEN_ORPHANS_13_SIDED_WAIT: { yaku: 13 },
  FOUR_QUADS: { yaku: 13 },
  NINE_GATES: { yaku: 13 },
  TRUE_NINE_GATES: { yaku: 13 },
  RIICHI: { yaku: 1 },
  DOUBLE_RIICHI: { yaku: 2 },
  IPPATSU: { yaku: 1 },
  ALL_SIMPLES: { yaku: 1 },
  PURE_STRAIGHT: { yaku: 2 },
  ALL_TRIPLETS: { yaku: 2 },
  HALF_FLUSH: { yaku: 3 },
  FULL_FLUSH: { yaku: 6 },
  SEVEN_PAIRS: { yaku: 2 },
  HALF_OUTSIDE_HAND: { yaku: 2 },
  FULLY_OUTSIDE_HAND: { yaku: 3 },
  PURE_DOUBLE_SEQUENCE: { yaku: 1 },
  TWICE_PURE_DOUBLE_SEQUENCE: { yaku: 3 },
  PURE_TRIPLE_SEQUENCE: { yaku: 1 },
  PURE_QUADRUPLE_SEQUENCE: { yaku: 3 },
  MIXED_TRIPLE_SEQUENCE: { yaku: 2 },
  THREE_CONCEALED_TRIPLETS: { yaku: 2 },
  THREE_QUADS: { yaku: 2 },
  TRIPLE_TRIPLETS: { yaku: 2 },
  SEAT_WIND: { yaku: 1 },
  PREVALENT_WIND: { yaku: 1 },
  NORTH_WIND: { yaku: 1 },
  WHITE_DRAGON: { yaku: 1 },
  GREEN_DRAGON: { yaku: 1 },
  RED_DRAGON: { yaku: 1 },
  NO_CALLS_TSUMO: { yaku: 1 },
  ROBBING_A_KAN: { yaku: 1 },
  UNDER_THE_SEA: { yaku: 1 },
  UNDER_THE_RIVER: { yaku: 1 },
  AFTER_A_FLOWER: { yaku: 1 },
  AFTER_A_KAN: { yaku: 1 },
  DORA: { dora: 1 },
  URA_DORA: { dora: 1 },
  CLOSED_WAIT: { fu: 2 },
  EDGE_WAIT: { fu: 2 },
  PAIR_WAIT: { fu: 2 },
  SIMPLE_OPEN_TRIPLET: { fu: 2 },
  ORPHAN_OPEN_TRIPLET: { fu: 4 },
  SIMPLE_CLOSED_TRIPLET: { fu: 4 },
  ORPHAN_CLOSED_TRIPLET: { fu: 8 },
  SIMPLE_OPEN_QUAD: { fu: 8 },
  ORPHAN_OPEN_QUAD: { fu: 16 },
  SIMPLE_CLOSED_QUAD: { fu: 16 },
  ORPHAN_CLOSED_QUAD: { fu: 32 },
  YAKUHAI_PAIR: { fu: 2 },
  CLOSED_PINFU: { yaku: 1 },
  OPEN_PINFU: { fu: 2 },
  NO_CALLS_RON: { fu: 10 },
  NON_PINFU_TSUMO: { fu: 2 },
};

const riichi_preset = {
  game_length_wind_rounds: 1,
  game_length_sub_rounds: 0,
  use_flowers: false,
  auto_replace_flowers: true,
  min_yaku: 1,
  allow_riichi: true,
  riichi_cost: 1000,
  can_riichi_negative_score: false,
  allow_rob_added_kan: true,
  allow_thirteen_orphans_rob_closed_kan: true,
  allow_rob_closed_kan: false,
  use_temporary_furiten: true,
  use_riichi_furiten: true,
  use_own_discard_furiten: true,
  end_last_round_if_dealer_ahead: true,
  show_waits: true,
  max_kan_count: 4,
  max_dora_count: 5,
  start_dora_count: 1,
  dead_wall_additional_tiles: 0,
  calculate_fu: true,
  base_fu: 20,
  round_up_fu: true,
  seven_pairs_use_fixed_fu: true,
  seven_pairs_fixed_fu: 25,
  round_up_points: true,
  show_shanten_info: false,
  base_score_limits: [
    { han: 5, score: 2000 },
    { han: 6, score: 3000 },
    { han: 8, score: 4000 },
    { han: 11, score: 6000 },
    { han: 13, score: 8000 },
  ],
  pattern_data: fill_in(riichi_pattern_data),
};

export const riichi_4player_preset: GameOptions = {
  ...riichi_preset,
  player_count: 4,
  start_score: 25000,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 2,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1,
  score_nondealer_tsumo_dealer_multiplier: 2,
};

export const riichi_3player_preset: GameOptions = {
  ...riichi_preset,
  player_count: 3,
  start_score: 35000,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 3,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1.5,
  score_nondealer_tsumo_dealer_multiplier: 2.5,
};
